### ISSUE TITLE
按照2.0官网指导，初始化后报错，页面空白

### ISSUE THREAD

**Issue by zhouzhili** [vuepress-reco/vuepress-theme-reco#33]
按照2.0主题进行初始化后报错
```bash
npm install @vuepress-reco/theme-cli@1.0.7 -g
theme-cli init
```
只有公告栏显示，主页面空白，控制台有2条报错信息：
ReferenceError: Cannot access 'clientAppEnhances' before initialization
Error: useRouteLocale() is called without provider.

**Comment by 1153606328** [comment]
解决了吗？我也遇到了

**Comment by 1153606328** [comment]
cofig.ts 注释掉 theme: 'reco', 可以正常运行vuepress默认的主题，，，但这并没有解决问题

**Comment by zhouzhili** [comment]
> cofig.ts 注释掉 theme: 'reco', 可以正常运行vuepress默认的主题，，，但这并没有解决问题

没解决，换了另外一个主题用了，放弃这个了

**Comment by googidaddy** [comment]
> > cofig.ts 注释掉 theme: 'reco', 可以正常运行vuepress默认的主题，，，但这并没有解决问题
> 
> 没解决，换了另外一个主题用了，放弃这个了

老哥用哪个了？俺也在找一个支持md的

**Comment by zhouzhili** [comment]
> > > cofig.ts 注释掉 theme: 'reco', 可以正常运行vuepress默认的主题，，，但这并没有解决问题
> > 
> > 
> > 没解决，换了另外一个主题用了，放弃这个了
> 
> 老哥用哪个了？俺也在找一个支持md的

用了vdoing 这个主题，也比较简单

**Comment by 1153606328** [comment]
用的reco 1.x版本 ，2.x版本还不太稳定&nbsp;

怎么去拥抱一夏天的风


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月8日(星期五) 上午10:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [vuepress-reco/vuepress-theme-reco] 按照2.0官网指导，初始化后报错，页面空白 (Issue #33)





    
cofig.ts 注释掉 theme: 'reco', 可以正常运行vuepress默认的主题，，，但这并没有解决问题
  
没解决，换了另外一个主题用了，放弃这个了
  
老哥用哪个了？俺也在找一个支持md的
  
用了vdoing 这个主题，也比较简单

**Comment by MakingBugs** [comment]
我也是

**Comment by censujiang** [comment]
我也一样，希望作者解决 @recoluan

**Comment by googidaddy** [comment]
我解决了，换了一个环境重新yarn后build就可以了。估计是之前依赖有问题。

**Comment by censujiang** [comment]
> 

换什么环境？详细描述一下谢谢

**Comment by censujiang** [comment]
> 我解决了，换了一个环境重新yarn后build就可以了。估计是之前依赖有问题。

麻烦详细说一下谢谢了

**Comment by googidaddy** [comment]
> 

原先我是在服务器上完成编译部署的，然后现在将项目除了node_modules这种类似的依赖之外的东西复制到了本地，重新build就可以了

**Comment by censujiang** [comment]
那你的意思就是说，只要变成Linux环境就行了？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月23日(周六) 中午12:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [vuepress-reco/vuepress-theme-reco] 按照2.0官网指导，初始化后报错，页面空白 (Issue #33)




   
原先我是在服务器上完成编译部署的，然后现在将项目除了node_modules这种类似的依赖之外的东西复制到了本地，重新build就可以了

**Comment by googidaddy** [comment]
> 那你的意思就是说，只要变成Linux环境就行了？
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年4月23日(周六) 中午12:49 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [vuepress-reco/vuepress-theme-reco] 按照2.0官网指导，初始化后报错，页面空白 (Issue #33) 原先我是在服务器上完成编译部署的，然后现在将项目除了node_modules这种类似的依赖之外的东西复制到了本地，重新build就可以了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

啊兄弟，学点基本项目初始化吧，我的意思相当于重新clone，复制更改的文件合并，重新装依赖。

**Comment by censujiang** [comment]
> > 那你的意思就是说，只要变成Linux环境就行了？
> > […](#)
> > ---原始邮件--- 发件人: _**@**_._**> 发送时间: 2022年4月23日(周六) 中午12:49 收件人: _**@**_.**_>; 抄送: _**@**_._**_**@**_.**_>; 主题: Re: [vuepress-reco/vuepress-theme-reco] 按照2.0官网指导，初始化后报错，页面空白 (Issue #33) 原先我是在服务器上完成编译部署的，然后现在将项目除了node_modules这种类似的依赖之外的东西复制到了本地，重新build就可以了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> 
> 啊兄弟，学点基本项目初始化吧，我的意思相当于重新clone，复制更改的文件合并，重新装依赖。

你自己又没说清楚，你就说项目初始化不就完了吗，你说换环境我一下子联系到依赖所需的系统环境

**Comment by recoluan** [comment]
同学，将 vuepress 和 reco 主题都升级到最新的beta版本，分别是 2.0.0-beta.39 和 2.0.0-beta.5，清除一下 node_modules ，lock 文件，以及 .vuepress 文件夹下的两个缓存文件夹，重新 install 。

**Comment by googidaddy** [comment]
> > > 那你的意思就是说，只要变成Linux环境就行了？
> > > […](#)
> > > ---原始邮件--- 发件人: _**@**_._**> 发送时间: 2022年4月23日(周六) 中午12:49 收件人: _**@**_.**_>; 抄送: _**@**_._**_**@**_.**_>; 主题: Re: [vuepress-reco/vuepress-theme-reco] 按照2.0官网指导，初始化后报错，页面空白 (Issue #33) 原先我是在服务器上完成编译部署的，然后现在将项目除了node_modules这种类似的依赖之外的东西复制到了本地，重新build就可以了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> > 
> > 
> > 啊兄弟，学点基本项目初始化吧，我的意思相当于重新clone，复制更改的文件合并，重新装依赖。
> 
> 你自己又没说清楚，你就说项目初始化不就完了吗，你说换环境我一下子联系到依赖所需的系统环境

捏马，重新装依赖环境，哪怕看到yarn后build都知道是啥意思吧，npm/yarn管理依赖的时代，系统哪门子有事。

**Comment by censujiang** [comment]
捏妈妈的，我上回npm build结果发现搞不了，然后发现有人往npm包里面塞了exe，这我上哪说理去？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月26日(周二) 中午11:34
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [vuepress-reco/vuepress-theme-reco] 按照2.0官网指导，初始化后报错，页面空白 (Issue #33)




    
那你的意思就是说，只要变成Linux环境就行了？
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2022年4月23日(周六) 中午12:49 收件人: _@**._&gt;; 抄送: ***@***.***@._&gt;; 主题: Re: [vuepress-reco/vuepress-theme-reco] 按照2.0官网指导，初始化后报错，页面空白 (Issue #33) 原先我是在服务器上完成编译部署的，然后现在将项目除了node_modules这种类似的依赖之外的东西复制到了本地，重新build就可以了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _@_.*&gt;
  
啊兄弟，学点基本项目初始化吧，我的意思相当于重新clone，复制更改的文件合并，重新装依赖。
  
你自己又没说清楚，你就说项目初始化不就完了吗，你说换环境我一下子联系到依赖所需的系统环境
  
捏马，重新装依赖环境，哪怕看到yarn后build都知道是啥意思吧，npm/yarn管理依赖的时代，系统哪门子有事。

**Comment by googidaddy** [comment]
> 

捏马🤏，无关话题不要强行拉进来。jpg

**Comment by recoluan** [comment]
将 vuepress 和 reco 主题都升级到最新的beta版本，分别是 2.0.0-beta.46 和 2.0.0-beta.16，清除一下 node_modules ，lock 文件，以及 .vuepress 文件夹下的两个缓存文件夹，重新 install 。

**Comment by 1153606328** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by censujiang** [comment]
顺带一提，包里塞exe不是这个项目的事情，是另外一个



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月26日(周二) 中午11:34
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [vuepress-reco/vuepress-theme-reco] 按照2.0官网指导，初始化后报错，页面空白 (Issue #33)




    
那你的意思就是说，只要变成Linux环境就行了？
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2022年4月23日(周六) 中午12:49 收件人: _@**._&gt;; 抄送: ***@***.***@._&gt;; 主题: Re: [vuepress-reco/vuepress-theme-reco] 按照2.0官网指导，初始化后报错，页面空白 (Issue #33) 原先我是在服务器上完成编译部署的，然后现在将项目除了node_modules这种类似的依赖之外的东西复制到了本地，重新build就可以了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _@_.*&gt;
  
啊兄弟，学点基本项目初始化吧，我的意思相当于重新clone，复制更改的文件合并，重新装依赖。
  
你自己又没说清楚，你就说项目初始化不就完了吗，你说换环境我一下子联系到依赖所需的系统环境
  
捏马，重新装依赖环境，哪怕看到yarn后build都知道是啥意思吧，npm/yarn管理依赖的时代，系统哪门子有事。
